language: node_js
node_js:
  - "stable"

install: npm install

services:
  -postgresql

env:
  -NODE_ENV=test

script: npm test

cache:
  directories:
    - "node_modules"
after_success:
  npm run coverage 